INSERT INTO locations (city, country) VALUES ('Moscow', 'Russia');
INSERT INTO locations (city, country) VALUES ('Pavlodar', 'Kazakhstan');
INSERT INTO locations (city, country) VALUES ('Almaty', 'Kazakhstan');
INSERT INTO locations (city, country) VALUES ('New York', 'United States');
INSERT INTO locations (city, country) VALUES ('Tokyo', 'Japan');
INSERT INTO locations (city, country) VALUES ('London', 'United Kingdom');
INSERT INTO locations (city, country) VALUES ('Paris', 'France');
INSERT INTO locations (city, country) VALUES ('Berlin', 'Germany');
INSERT INTO locations (city, country) VALUES ('Sydney', 'Australia');
INSERT INTO locations (city, country) VALUES ('Dubai', 'United Arab Emirates');
INSERT INTO locations (city, country) VALUES ('Beijing', 'China');
INSERT INTO locations (city, country) VALUES ('Rome', 'Italy');
INSERT INTO locations (city, country) VALUES ('Madrid', 'Spain');
INSERT INTO locations (city, country) VALUES ('Toronto', 'Canada');
INSERT INTO locations (city, country) VALUES ('Seoul', 'South Korea');
INSERT INTO locations (city, country) VALUES ('Sao Paulo', 'Brazil');
INSERT INTO locations (city, country) VALUES ('Mumbai', 'India');
INSERT INTO locations (city, country) VALUES ('Mexico City', 'Mexico');
INSERT INTO locations (city, country) VALUES ('Cairo', 'Egypt');
INSERT INTO locations (city, country) VALUES ('Bangkok', 'Thailand');
INSERT INTO locations (city, country) VALUES ('Lagos', 'Nigeria');
INSERT INTO locations (city, country) VALUES ('Buenos Aires', 'Argentina');
INSERT INTO locations (city, country) VALUES ('Istanbul', 'Turkey');
INSERT INTO locations (city, country) VALUES ('Shanghai', 'China');
INSERT INTO locations (city, country) VALUES ('Jakarta', 'Indonesia');
INSERT INTO locations (city, country) VALUES ('Los Angeles', 'United States');